[package]
name = "libva-rust"
version = "0.0.1"
authors = ["Hyunjun Ko <zzoon@igalia.com>"]

[lib]
name = "libva_rust"
path = "src/lib.rs"

[dependencies.libc]
version = "0.2.74"

[dependencies.x11]
version = "2.18.2"
features = ["xlib"]
